### ISSUE TITLE
Installation problem: Unable to read repository: No exists content.xml

### ISSUE THREAD

**Issue by KaLuck** [de-jcup/eclipse-bash-editor#147]
Hi Albert,

 I see that exists similar issues with this URL, and I follow yous steps, by at this moment, when I want installed on "Eclipse IDE for Enterprise Java Developers.:: Version: 2018-12 (4.10.0)",
Eclipse advertise me:
"Unable to read repository
"Unable to read repository at https://dl.bintray.com/de-jcup/basheditor/content.xml.
Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"

 And if you go to this URL  with browser you can see "The requested path was not found." ; same notice with "http://" .

Of course, I can continue the installation, but, Why this error on installation? Is a bug? Is a knowed bug and can i install without compromise the pc?

 Thanks for you patience and regards.

P.D: Sorry by my poor english.

**Comment by de-jcup** [comment]
Hello @KaLuck 
You are right, https://dl.bintray.com/de-jcup/basheditor/content.xml does not exist. But instead there exists
https://dl.bintray.com/de-jcup/basheditor/content.jar which contains` content.xml` inside...

Eclipse has a fallback when not able read to read `content.jar` it will try to read a `content.xml` file . But the problem is not the unexisting xml file but the security exception:

> Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"

The problems seems to be at your used java version. There are many descriptions how to handle this problem. For example after searching for the "Unexpected ...." text I found something like this as first result: https://askubuntu.com/questions/971059/17-10-openjdk-and-oracle-jdk-8-and-9-the-trustanchors-parameter-must-be-non-empt

So after fixing your java setup it should work with https

**Comment by KaLuck** [comment]
Hi,

 Finally the problem was a bad generation of cacerts. To resolved it, the easy way, was to use a Oracle Java cacerts and not of Open-JDK 11. This problem was generated with Openjdk-11, during installation to create a cacerts, on Debian 9; in my pc, one of configures file, "jks-keystore", show error. Well, when this problem was resolved, the installation of Bash Editor, notice me a typical warning about unsigned plugin installation, but in other post of "2018-01-29" in Eclipse marketplace, you said "is normal because I currently do not sign my plugins", ok .

 Thanks for all.
Regards.

**Comment by de-jcup** [comment]
You are wellcome.
