### ISSUE TITLE
Second if statement  not coloured

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#16]
In this piece of code, the second if statament  is not coloured

  ``` bash
 if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
        DIST=$(grep "DISTRIB_ID" /etc/lsb-release|awk -F"=" '{print $2}'|tr -d "\"', \n")
        if [ -z "$DIST" ]; then
            DIST="Ubuntu"
        fi
fi
```
![image](https://user-images.githubusercontent.com/11644753/29508379-a19d6c4a-8654-11e7-87d3-8a9259662881.png)

(original bug information came from https://marketplace.eclipse.org/comment/4750#comment-4750)

**Comment by de-jcup** [comment]
Also "lsb-release" is not correct colored (it is NOT an argument!)

**Comment by cwilliamson62** [comment]
I cannot find bash editor in the list of internal editors after installation. I cannot see any bash in the eclipse preferences. I don't know how to open a file with bash editor because it is not a choice. I am on Eclipse version Oxygen.1a Release (4.7.1a). Is there some prerequisite or something that I am missing? Thanks a ton for any help you might offer.
Chris

**Comment by de-jcup** [comment]
@cwilliamson62 I created an own issue for your problem at https://github.com/de-jcup/eclipse-bash-editor/issues/76 I will try to help you there.
