### ISSUE TITLE
Attempted installation of plugin fails with "unable to find valid certification path to requested target"

### ISSUE THREAD

**Issue by davidmichaelkarr** [de-jcup/eclipse-bash-editor#182]
I'm trying to install this plugin from the marketplace today, and it's failing with the following:

Unable to read repository at https://dl.bintray.com/de-jcup/basheditor/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I tried going this far with other plugins, and I'm not seeing this error.

**Comment by de-jcup** [comment]
Hello David,

I described the situation inside FAQ now, because this was asked very often.
See https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#install-fails-with-unable-to-read-repository-at 

The wiki links also an issue were a similar output was a problem: see https://github.com/de-jcup/eclipse-bash-editor/issues/147

**Comment by davidmichaelkarr** [comment]
Resolving this doesn't seem easy at all, using the provided instructions.  I don't see a clear path forward from this melange of information.  It might be easier for me to just clone the project and build it locally and install from a local update site.  Will it build on Windows?

**Comment by davidmichaelkarr** [comment]
I'm guessing the answer is no, although it just be an oversight.

When I ran ./gradlew build, I saw these three unit test failures:

```
de.jcup.basheditor.debug.launch.InternalTerminalCommandStringBuilderTest > context_3 FAILED
    org.junit.ComparisonFailure at InternalTerminalCommandStringBuilderTest.java:74

de.jcup.basheditor.debug.launch.InternalTerminalCommandStringBuilderTest > context_4 FAILED
    org.junit.ComparisonFailure at InternalTerminalCommandStringBuilderTest.java:90

de.jcup.basheditor.ExternalToolCommandArrayBuilderTest > anExistingFile_commands_are_as_expected_and_parameter_replaced FAILED
    org.junit.ComparisonFailure at ExternalToolCommandArrayBuilderTest.java:46
```

**Comment by davidmichaelkarr** [comment]
Is there any path forward from this?  The plugin as provided fails to install, and the FAQ doesn't help to resolve this, and I can't even build the code locally.

**Comment by de-jcup** [comment]
Hello David.

Here some answers:

1. For better understing, please give me information about
    - Your Eclipse version (variant (e.g. Java + version number)
    - Your Java version (vendor + version number)
    - Your OS version

2. Not able to install by marketplace
    - This is a little bit odd, because in february 2020 more than 1700 succesful installs where done, see 
https://marketplace.eclipse.org/content/bash-editor#group-metrics-tab

3. Other kind of installation ways
    - https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-install-bash-editor-offline
    - https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-install-bash-editor-automated

4. Local build not possible.
    - Build of plugin is not done by gradle, only testing... see https://github.com/de-jcup/eclipse-bash-editor/wiki/Contribution#separation-of-plain-java-and-eclipse-parts 
    - But of course the 3 tests should not fail on a windows machine, maybe its a path separator thing (I develop on linux machines)

**Comment by davidmichaelkarr** [comment]
I'm running Eclipse Java 2019-12, with Java 13, on Windows 10.

**Comment by davidmichaelkarr** [comment]
I was able to install the plugin by changing the update site url to http, instead of https.  I'm glad your site is lax on its security. :)

It sounds to me like bintray has a root certificate that Java 13 no longer honors by default.

**Comment by de-jcup** [comment]
## Java version
Hmm... Java13... would be interesting to get the vendor information as well. I had issues with OpenJDK because of initialy missing root certificates of wellknown vendors.

When using JDK/JRE from
- oracle 
- coretto 
- ...
where you have an LTE , the certificates used by bintray should be recognized and trusted.

## Usage of HTTP
"Lax on security" ... 
Bintray still supports http ... but... I would not recommend to install in such way.

**Secure way would be (imho):**
1. download the certificate offered by bintray site. Inspect content if it's correct - means signed by a trustful certificate provider (otherwise  you could be the victim of a "man in the middle " attack and somebody is providing wrong certificates... )
2. update your certificate store used by your JDK
3. install again - than it will work

Remark:
Of course I should sign my plugins as well... but currently it's not working, so at least I rely on trusted certificates from bintray + keeping my account credentials secret...

**Comment by davidmichaelkarr** [comment]
I went to https://bintray.com/ . I clicked on the lock icon and navigated to the cert and exported it.  I went to the shell and used keytool to import the cert into my cacerts file for the JDK I'm running Eclipse with.  I verified the file was modified afterwards.  I then restarted Eclipse. I uninstalled the plugin that I got from the http address.  I then went to the marketplace and tried to reinstall the plugin.  Same error.  No difference.

**Comment by de-jcup** [comment]
Hmm... this is an odd situation. Sorry, but currently I have no other suggestions/ideas for you - except to download the files by browser and create a local update site. This is already described at https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-install-bash-editor-offline

**Comment by de-jcup** [comment]
Are there any updates or can we closes this?

**Comment by davidmichaelkarr** [comment]
I think this ended up being an issue with our firewall. I believe your
server cert is self-signed, and it appears that our firewall blocks that. I
can do updates when my VPN is off.

**Comment by de-jcup** [comment]
Server cert is not self signed - it's from bintray which is very wellknown and keep their certificates up to date (JCenter maven repository is hosted there as well!)

I think  you were able to install now - so I close the issue
