### ISSUE TITLE
Describe how to show up debug view /perspective

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-bash-editor#216]
Will be done at https://github.com/de-jcup/eclipse-bash-editor/wiki/Debugger#i-cant-see-the-debug-and-breakpoint-view

We will use following images:
![image](https://user-images.githubusercontent.com/11644753/90241928-538e8d80-de2c-11ea-947c-4e626c3e73df.png)

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/90242476-69508280-de2d-11ea-8ea2-c13d88d74917.png)

**Comment by de-jcup** [comment]
![image](https://user-images.githubusercontent.com/11644753/90242614-a3ba1f80-de2d-11ea-94df-e89a53dec5d8.png)

**Comment by cristalp** [comment]
It would be great if this would happen automatically, as in Java. The first time you debug, Eclipse asks you whether you want to open the Debug perspective. If you choose to do that and save that decision, it works automatically from then on.
The problem is (for me) that my debug view doesn't show the various Explorer views, so I can't just switch to the Debug perspective and start a new debugging sessions, since I don't see the files.

**Comment by de-jcup** [comment]
@cristalp : i created issue #269 to automatically bring up the debug perspective on bash debug sessions. It will come with next release.

**Comment by cristalp** [comment]
Great, thanks a lot!
