### ISSUE TITLE
Associate/support fish shell

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-bash-editor#85]
Associate/support fish shell http://fishshell.com/  (`.fish` filename extension )  
example of usage in https://github.com/apache/struts-site

**Comment by de-jcup** [comment]
Hello @paulvi , 

The fish shell syntax is not exactly syntax comptabile with bash. So if the bash editor  works for you as an adequate  editor for fish scripts - okay...  but I will not support this officially because maybe something break. This is mentioned now inside the FAQ see https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#why-is-bash-editor-not-automatically-associated-with-other-script-file-types 

There is also described how to create the file association by user itself:

> 
> Anyway, if you want to associate other script files with bash editor you can do this the standard way, by
> `Window->Preferences->"file"->Add->*.fish as shown` in next picture:  
> ![image](https://user-images.githubusercontent.com/11644753/33759753-bb97c0c8-dc03-11e7-9c1c-d8b721796eee.png)  
> Then add associated editor:  
> ![image](https://user-images.githubusercontent.com/11644753/33759673-76943808-dc03-11e7-975b-3a289ae247a6.png)
> 
>
