### ISSUE TITLE
Should site.xml be located at top of tree?

### ISSUE THREAD

**Issue by dalesit** [de-jcup/eclipse-bash-editor#99]
I have been trying to automate installation of eclipse plugins for a vagrant build of our developer VM environment. I have been doing this using p2-director, and for most plugins it is fine. However, for BashEditor it is failing, saying that the IU can't be found.

```
!SESSION 2018-01-18 16:23:16.046 -----------------------------------------------
eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product -application org.eclipse.equinox.p2.director -repository https://dl.bintray.com/de-jcup/basheditor -installIU de.jecup.basheditor.feature.group
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product -application org.eclipse.equinox.p2.director -repository https://dl.bintray.com/de-jcup/basheditor -installIU de.jecup.basheditor.feature.group

!ENTRY org.eclipse.equinox.p2.director.app 4 0 2018-01-18 16:23:21.043
!MESSAGE The installable unit de.jecup.basheditor.feature.group has not been found.
```

For yedit, for example, the site.xml is located at the top of the update site, http://dadacoalition.org/yedit/site.xml which is at the same level as the features directory. However, here, the site.xml is located at https://dl.bintray.com/de-jcup/basheditor/update-site/current/site.xml but the feature location is given as feature url="features/de.jcup.basheditor_1.0.0.jar" but is two directories higher up.

Using a manual Install New Software from within Eclipse and giving the update site URL, it works fine. However, automating it through p2-director fails. 

The full command I am running is
` /opt/eclipse/eclipse -application org.eclipse.equinox.p2.director -noSplash -repository 'https://dl.bintray.com/de-jcup/basheditor' -installIU 'de.jecup.basheditor.feature.group'`

The p2 documentation suggests
```
Arguments Description
-application org.eclipse.equinox.p2.director: the application ID.
-metadataRepository: a comma separated list of metadata repository URLs where the software to be installed can be found.
-artifactRepository: a comma separated list of artifact repository URLs where the software artifacts can be found.
-repository: a comma separated list of repository URL where each entry denotes colocated meta-data and artifact repositories.
```
however I have tried with a separated -metadataRepository and still no joy.
Any suggestions?

**Comment by de-jcup** [comment]
Hello @dalesit ,

I have no experience with org.eclipse.equinox.p2.director , but I have seen something in your command which seems to be a typo:

#### Your command:
> /opt/eclipse/eclipse -application org.eclipse.equinox.p2.director -noSplash -repository 'https://dl.bintray.com/de-jcup/basheditor' -installIU 'de.j**e**cup.basheditor.feature.group'

There is following typo: "de.j**e**cup" instead of "de.jcup" )

#### My suggestion:
/opt/eclipse/eclipse -application org.eclipse.equinox.p2.director -noSplash -repository 'https://dl.bintray.com/de-jcup/basheditor' -installIU 'de.jcup.basheditor.feature.group'

#### Additional information
I think that if you can install something by eclipse marketplace client the p2.director should be always able to install it too - the marketplace client must use p2 in same way as director and there must be no difference at all - otherwise there would be different install implementations and behaviours and this would be really done wrong by eclipse developers.

By the way current version is 1.4.1 and in the next days Bash editor version 1.5.0 will be deployed having bug fixes and also some new features like keyword tooltips - so please do not use version 1.0 (you mentioned "features/de.jcup.basheditor_1.0.0.jar" in your text before) in your vagrant installation.

**Comment by dalesit** [comment]
Thank you so much for spotting the typo - as I said, this was the first of many plugins that hadn't worked, and so I was looking for differences between them, and the different location of site.xml seemed to be a possible candidate. After looking at the text for so long, I completely missed the typo in the IU - I had originally cut and pasted into the puppet manifest and must have spuriously added the e. From there I just took the output of the puppet apply to generate the actual p2-director command, and never noticed the IU typo #facepalm.

The mention of "features/de.jcup.basheditor_1.0.0.jar" was just as an example, and was the first one in site.xml which I cut and pasted - I'm installing the latest version available.

The .feature.group doesn't matter - it works with  -installIU 'de.jcup.basheditor' and ignores everything after that. 

So once again, thanks for your assistance - l need to replace my cardboard programmer...

BTW, would be helpful to add the IU and update site information to the wiki (and possibly the p2-director install command) should anyone be trying to do this again

/opt/eclipse/eclipse -application org.eclipse.equinox.p2.director -noSplash -repository 'https://dl.bintray.com/de-jcup/basheditor' -installIU 'de.jcup.basheditor'

**Comment by de-jcup** [comment]
I added an FAQ entry : https://github.com/de-jcup/eclipse-bash-editor/wiki/FAQ#how-can-i-install-bash-editor-automated
